# Generated by Django 3.1.1 on 2020-10-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='categories',
            field=models.PositiveSmallIntegerField(choices=[(1, 'podstawówka klasy 1-4'), (2, 'podstawówka klasy 5-8'), (3, 'liceum poziom podstawowy'), (4, 'liceum poziom rozszerzony')], default=1),
        ),
    ]
